runtime : custom 
env : flex
service : "inventory"
automatic_scaling :
  min_num_instances : 1
  max_num_instances : 2  # Adjust based on expected traffic and cost considerations
  target_cpu_utilization : 0.65  # You can tune this value to avoid over-provisioning instances
  target_throughput_utilization : 0.75
