runtime : custom 
env : flex
service : "inventory"
automatic_scaling :
  min_num_instances : 1
  max_num_instances : 2  # Adjust based on expected traffic and cost considerations
  cpu_utilization :  # You can tune this value to avoid over-provisioning instances
    target_utilization : 0.75
