# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Install .NET 8.0 SDK
        run:|
          wget https://packages.microsoft.com/config/ubuntu/22.04/prod.list
          sudo mv prod.list /etc/apt/sources.list.d/dotnetdev.list
          wget https://packages.microsoft.com/keys/microsoft.asc
          sudo apt-key add microsoft.asc
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
          dotnet --version
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish the application
      run: dotnet publish inventory.csproj --configuration Release --output ./publish

      # Step 7: Set up Google Cloud authentication
    - name: Set up Google Cloud Authentication
      run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file /tmp/gcp-key.json
          gcloud config set project teak-environs-445405-g2
          
          

      # Step 8: Deploy to GCP App Engine
    - name: Deploy to Google Cloud App Engine
      run: |
          gcloud app browse || true  # Optional: Verify if App Engine is reachable
          gcloud app deploy ./publish/app.yaml --quiet 
